[project]
name = "online-document-signer"
version = "0.1.0"
description = "Online Document Signer"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "beanie",
    "fastapi[standard]",
    "motor",
    "python-dotenv",
    "python-multipart",
    "pymongo",
    "requests",
    "pymupdf",
    "Pillow",
    "streamlit-drawable-canvas",
    "streamlit>=1.40.0",
]
[tool.mypy]
[[tool.mypy.overrides]]
module = "fitz"
ignore_missing_imports = true
mypy_path = "Backend"
